Side bar
atomata/capstone_WebClient pull request #56
Opened 2022-02-07 22:42 UTC by shushengfuqin

### Summary 
This is just a pr which contains the basic part of the new UI.
They are in the new folder under src called UIComponent. 
Please becareful with the naming convention and how the files are placed.

### Details
Action bar: the bar on the left which contains the buttons to change the content in the sidebar
Side bar: the togglebal container which contains different element based on the button clicked in the action bar
Textbox : the text box
ActionSequence"
### How to test?
There not much to be tested, However if you need to work on the unity and have the previous things, just go in the webglbox.tsx and uncomment the overlay and comment the ActionBar.
### Checks 
- [ ] Tested Changes
- [ ] Stakeholder Approval

2022-02-19 13:02 UTC, Ysabz requested changes
Please put all the new UI components in a separate folder for now for a cleaner folder structure

2022-02-19 13:02 UTC, Ysabz commented on src/util/customHooks/ActionBarFunc.tsx
> +    if (tooDoc === false) {
typo

2022-02-19 13:11 UTC, Ysabz commented
The page does not fit on the screen ( there are side scrollbars no matter what Zoom I use) 
![image](https://user-images.githubusercontent.com/44596199/154802213-e87964d8-c540-4172-b177-dcf54f994859.png)

2022-02-19 13:12 UTC, Ysabz commented
This PR needs to integrate the new selection page and text box

2022-02-19 13:13 UTC, Ysabz commented
> The page does not fit on the screen ( there are side scrollbars no matter what Zoom I use) ![image](https://user-images.githubusercontent.com/44596199/154802213-e87964d8-c540-4172-b177-dcf54f994859.png)

also, in the side bar, what is the second button from top doing?

2022-02-19 13:17 UTC, Ysabz commented
problems with action sequence :

- the place holders in the action sequence are not necessary. 
- the color of elements in action sequence need to be consistent with mockup
- The action sequence is not scrollable and draggable 
- not connected with other components

2022-02-19 16:33 UTC, shushengfuqin commented on src/components/UIComponent/SideBarItem.tsx
> +  const { actionList } = useActionList(experienceData);
True, 
I'll make it as context in this case.

2022-02-19 16:34 UTC, shushengfuqin commented on src/components/UIComponent/Action Sequence 2.0/ActionSequenceItem.tsx
> +function ActionSequenceItem({name,action}:ActionSequenceItemProps): JSX.Element {
that i have no idea, it was merged from what Justin did. I'll double-check to make sure.

2022-02-19 16:34 UTC, shushengfuqin commented on src/components/UIComponent/Action Sequence 2.0/ActionSequence.tsx
> +      {/* <DragDropContext onDragEnd={handleOnDragEnd}>
It was commented by justin, I am not sure why.

2022-02-19 18:48 UTC, shushengfuqin commented on src/util/customHooks/ActionBarFunc.tsx
> +    if (tooDoc === false) {
resolved

2022-02-19 18:48 UTC, shushengfuqin commented on src/components/UIComponent/SideBar.tsx
> +    tooDoc,
tooDoc -> toolDoc
resolved

2022-02-20 02:16 UTC, shushengfuqin commented on package.json
> +    "@material-ui/core": "^4.12.3",
will be removed

2022-02-20 02:16 UTC, shushengfuqin commented on src/util/customHooks/SideBarContext.tsx
> +import { createContext } from "react";
easier to manage.

2022-02-20 02:18 UTC, shushengfuqin commented on src/components/UIComponent/Action Sequence 2.0/ActionSequence.tsx
> +                        {/* <List>
i'm not sure if justin need them or not

2022-02-20 02:23 UTC, shushengfuqin commented on src/components/UIComponent/ApparatusInfo.tsx
> +    useActionList(experienceData);
this is the part that we need useContext i guess? to share the values

2022-02-21 02:59 UTC, merged

2022-02-21 03:00 UTC, Ysabz reviewed
Works fine. needs to be enhaned in a another PR