Texteditor v1
atomata/capstone_WebClient pull request #60
Opened 2022-02-16 03:13 UTC by Ysabz

### Summary 
This PR add the text editor to save/modify text for each action in the action sequence
### Details
_Fixes the  WebgL input consumption bug
_ adds the styled text editor to the editor page 
_ allows saving and viewing the text for each action
### How to test?
_create new experience , add some texts to different actions in action sequence ( save the texts) , save the experience, then reload the experience and check if the texts are there for each action
### Checks 
- [ ] Tested Changes
- [ ] Stakeholder Approval

2022-02-17 03:00 UTC, mckenzietsean requested changes

2022-02-17 03:00 UTC, mckenzietsean commented on src/components/WebglBox.tsx
> +      <Overlay userId={userId} experienceData={experienceData} tabIndex={1} />
Azure Static Web Apps CI/CD detected an error when trying to compile this branch.

**Type error: Type '{ userId: string; experienceData: ExperienceData; tabIndex: number; }' is not assignable to type 'IntrinsicAttributes & OverlayProps'.
  Property 'tabIndex' does not exist on type 'IntrinsicAttributes & OverlayProps'.**

2022-02-18 04:29 UTC, Ysabz commented on src/components/TextEditor.tsx
> +                  actionList[selectedAction].desc = currDesc;
fixed this error. also refactored currdesc state variable and moved it to texteditor component

2022-02-18 04:43 UTC, mckenzietsean approved these changes
A few minor nitpicks but the general functionalities are good.

2022-02-18 16:59 UTC, merged